#!/bin/bash
# creates symlinks from here to ~/bin/*
for x in $(ls); do
	if [ "$x" == "symlinker" ]; then
		continue;
	fi
	if [ "$x" == "README.md" ]; then
		continue;
	fi
	ln -s "$(dirname $(realpath $0))/$x" "$HOME/bin/$x"
done
